spring:
  session:
    jdbc:
      initialize-schema: always # 스프링 부트가 세션을 자동 생성하도록 설정

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: # JPA 설정
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${JWT_SECRET} # JWT SECRET키

openai:
  model : gpt-3.5-turbo
  api :
    key : ${OPENAI_API_KEY}
    url : https://api.openai.com/v1/responses
